echo "We are trying this practical from linux EC2"
echo "We are from batch-33 and learning git/gihub"
echo "We are learning Branching"
echo "I am learning Git"
echo "I am staying before pune"
echo "I am learning git branching conflict and Merge request"